export const routes = {
  index: "/",
  login: "/login",
  settings: "/settings",
  approvals: "/approvals",
  events: "/events",
  requisitions: "/requisitions",
  academicRecords: "/academicRecords",
  registerSchool: "/register",
  schools: "/schools",
  departments: "/departments",
  courses: "/courses",
  classes: "/classes",
  staff: "/staff",
  singleStaff: "/staff/:staffId",
  singleStudent: "/students/:studentId",
  singleStudentCourseParticipantRecord:
    "/students/:studentId/course-participant-record/course/:courseId/class/:classId",
  singleStudentSingleClassOverview:
    "/students/:studentId/class-overview/:classId",
  singleStudentSingleSessionResult: "/students/:studentId/session-result",
  sessions: "/sessions",
  assessments: "/assessments",
  singleCustodian: "/custodians/:custodianId",

  custodians: "/custodians",
  students: "/students",
  singleClassCourse: `/classes/:classId/courses/:courseId`,
  singleClass: `/classes/:classId`,
  singleStaffClass: `/classes/:classId/staff/:staffId`,
  policies: `/policies`,
  payments: `/payments`,
  reports: `/reports`,
  announcements: `/announcements`,
  assignSessionCoursesToStudent: `/students/:studentId/assign-course`,
  assignSessionCoursesToStaff: `/staff/:staffId/assign-course`,
};
