export const routes = {
  index: "/",
  login: "/login",
  // schools: "/schools/",
  departments: "/departments/",
  courses: "/courses/",
  classes: "/classes/",
  staff: "/staff/",
  singleStaff: "/staff/:staffId",
  sessions: "/sessions/",
  assessments: "/assessments/",
  custodians: "/custodians/",
  students: "/students/",
  singleClassCourse: `/classes/:classId/courses/:courseId`,
  singleClass: `/classes/:classId`,
  policies: `/policies`,
  payments: `/payments`,
};
